---
- name: Update packages list
  apt: update_cache=yes
  become: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

