---
- name: Disable SWAP
  shell: swapoff -a
  become: yes

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  become: yes

- name: Import sysctl k8s configuration
  template:
    src: ../templates/k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  become: yes
  notify:
    - Restart sysctl

- name: Run setHost.sh
  script: ../scripts/setHost.sh
  args:
    executable: bash
  become: yes

