---
- name: Create directory for kube config
  file: 
    path: /home/vagrant/.kube
    state: directory
    owner: "vagrant"
    group: "vagrant"
    mode: 0770
  become: yes

- name: Copy /etc/kubernetes/admin.conf to /home/vagrant/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: "vagrant"
    group: "vagrant"
  become: yes

